### ISSUE TITLE
Victory Condition

### ISSUE THREAD

**Issue by PascalCremer** [wotateam/wota#163]
At the moment the player with the most ants wins after the maximum number of ticks. Do we want it that way? 

I think its good from a game design point of view but also for performance since we can stop games relatively early without causing too many draws. I have seen some games 'converging' to a 2/3 1/3 ant population state. 

Its also better for many-player games where often some ais are dead and the remaining split 1/10, 1/10, 1/10, 7/10 or similar.

**Comment by LoadingPleaseWait** [comment]
It looks like this issue has been fixed for a while now.
